### ISSUE TITLE
AttributeError: 'module' object has no attribute 'PortScanner'

### ISSUE THREAD

**Issue by r3nhat** [milo2012/ipv4Bypass#1]
Hello,

Its seems to be a great tool which will save a lot of time during pentest.
But, i have an issue run this tool on Kali:

```
python bypass.py -i eth0 -r 192.168.2.0/24
Traceback (most recent call last):
  File "bypass.py", line 10, in <module>
    nm = nmap.PortScanner()
AttributeError: 'module' object has no attribute 'PortScanner'

```
Thank you!

**Comment by milo2012** [comment]
You likely installed the package "nmap", not "python-nmap":

So, just uninstall "nmap" and install "python-nmap”

pip uninstall nmap

pip install python-nmap

Let me know if it works

**Comment by r3nhat** [comment]
Hello,

Thanks for your reply!

I had both nmap and python-nmap installed.
What i did is to uninstall both and then: pip install python-nmap

Now is working.

Thank you!

**Comment by jingrena** [comment]
hello,
I also have this problem, but I have done your methods while it doesn't work

**Comment by fbbfnc** [comment]
> hello,
> I also have this problem, but I have done your methods while it doesn't work

Same here! I'm in a virtualenv by the way

**Comment by milo2012** [comment]
Please make sure you have installed python-nmap
pip install python-nmap

**Comment by CoderAtomCreator** [comment]
Requirement already satisfied: python-nmap in c:\users\atomsecurity\appdata\local\programs\python\python38-32\lib\site-packages (0.6.1) ... 
HELP PLEASE

**Comment by Mitch930** [comment]
> Requirement already satisfied: python-nmap in c:\users\atomsecurity\appdata\local\programs\python\python38-32\lib\site-packages (0.6.1) ...
> HELP PLEASE

Having the same problem. Help would be greatly appreciated.

**Comment by milo2012** [comment]
pip uninstall nmap
pip install python-nmap

That will fix the issue

**Comment by Ibizinis** [comment]
ns = nmap.PortScanner()
AttributeError: partially initialized module 'nmap' has no attribute 'PortScanner' (most likely due to a circular import)

I DID RE-INSTALLED MANY TIMES THE SAME WAY AS PEOPLE DID HERE, STILL GET THIS SHIT. HELP

**Comment by Ikenahim** [comment]
@Ibizinis if you still have the problem this will fix it for u,
-download python-nmap from here http://xael.org/pages/python-nmap-en.html
- unzip and cd to the folder
- open cmd command for windows and run python setup.py install
check the installed version by
-python install nmap-python 

goodluck

**Comment by Global-Occult** [comment]
> ns = nmap.PortScanner()
> AttributeError: partially initialized module 'nmap' has no attribute 'PortScanner' (most likely due to a circular import)
> 
> I DID RE-INSTALLED MANY TIMES THE SAME WAY AS PEOPLE DID HERE, STILL GET THIS SHIT. HELP

Did you name your script as nmap.py or python-nmap.py ?
Try changing the name

**Comment by TorhamDev** [comment]
Hello friends
In fact, you need to have the lamp installed on your operating system

For example, I use Fedora Linux
```bash
sudo dnf install nmap
```

You must have nmap installed on your operating system.



But if you still get the same error, follow these steps:

```bash
pip uninstall nmap
```
or
```bash 
pip uninstall python-nmap
```
and 
```bash
pip install -i https://mirrors.aliyun.com/pypi/simple/ python-nmap
```

I hope your problem is solved :)

**Comment by ghost** [comment]
Please note that if your project file is named 'nmap.py' and you are attempting to import the 'nmap' library (python-nmap), it may not function as expected. To resolve this issue, consider renaming your file.
