### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by darkmatter1505** [milo2012/ipv4Bypass#2]
I was running the bypass.py script and received this error. 

[*] Found the below IPv6 addresses
Traceback (most recent call last):
  File "bypass.py", line 245, in <module>
    print x+"\t"+tmpMacAddr
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by k1z1lelma** [comment]
I edited the code according to Python3. You can access the current version via the repo below:

https://github.com/k1z1lelma/ipv4bypass
