### ISSUE TITLE
Doesn't work on WiFi adaptor

### ISSUE THREAD

**Issue by NorthStarCyberSecurity** [milo2012/ipv4Bypass#4]
The interface value is not passed to the arp-scan command.

Change line 228 to 

cmd="/usr/sbin/arp-scan -I "+interfaceNo+" "+targetIP

Seems to work then

**Comment by rikosintie** [comment]
That fixed it for me! 

Milo2012 and NorthStarCyberSecurity, thanks so much for this. I have learned a lot by reviewing the code. I am going to learn about the socket library next. 

I have also been reviewing your smbinfo script. It's well beyond my skill level, but again, I am learning so much from it.
